{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "typesense.fullname" . }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.podDisruptionBudget.spec | nindent 2 }}
  selector:
    matchLabels:
      {{- include "typesense.selectorLabels" . | nindent 6 }}
{{- end }}
